### ISSUE TITLE
Latest doctrine-orm-module compatibilty

### ISSUE THREAD

**Issue by edigu** [Hounddog/DoctrineDataFixtureModule#45]
Require section of my composer.json is like below:

``` js
"require": {
        "php": ">=5.6",
        "zendframework/zendframework": "2.4.0",
        "doctrine/orm": "2.5.0",
        "doctrine/doctrine-module": "dev-master",
        "doctrine/doctrine-orm-module": "dev-master",
        "hounddog/doctrine-data-fixture-module": "dev-master"
    },
```

and composer update command produces this output:

``` bash
$ php composer.phar update      
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hounddog/doctrine-data-fixture-module dev-master requires doctrine/doctrine-orm-module ~0.7 -> no matching package found.
    - hounddog/doctrine-data-fixture-module dev-master requires doctrine/doctrine-orm-module ~0.7 -> no matching package found.
    - Installation request for hounddog/doctrine-data-fixture-module dev-master -> satisfiable by hounddog/doctrine-data-fixture-module[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

Currently its impossible to install **DoctrineDataFixtureModule** and **DoctrineORMModule** together.

**Comment by tad3j** [comment]
@edigu, I think you should be using latest versions:
doctrine/doctrine-module              0.8.1
doctrine/doctrine-orm-module          0.8.0
hounddog/doctrine-data-fixture-module dev-master

Those are the versions reported by composer and fixtures work as expected.

Here is require part of my composer.json (in case you'll wonder):
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "~2.4",
        "zf-commons/zfc-user-doctrine-orm": "~1.0",
        "zf-commons/zfc-rbac": "~2.4",
        "hounddog/doctrine-data-fixture-module":"dev-master"
    },
